FROM nvcr.io/nvidia/pytorch:23.04-py3

ENV http_proxy=http://137.153.170.55:10080/ \
    https_proxy=http://137.153.170.55:10080/ \
    HTTP_PROXY=http://137.153.170.55:10080/ \
    HTTPS_PROXY=http://137.153.170.55:10080/
    
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
apt-get install -y --no-install-recommends software-properties-common && \
add-apt-repository ppa:deadsnakes/ppa -y && \
apt-get update && \
apt-get install -y --no-install-recommends \
    python3.10 \
    python3.10-distutils \
    python3.10-dev && \
update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.10 1 && \
curl -sS https://bootstrap.pypa.io/get-pip.py | python3.10 && \
apt-get clean && rm -rf /var/lib/apt/lists/*

# Update GPG key of NVIDIA Docker Images 
# (See https://developer.nvidia.com/blog/updating-the-cuda-linux-gpg-repository-key/ for more detail)
RUN rm -f /etc/apt/sources.list.d/cuda.list \
 && apt-get update && apt-get install -y --no-install-recommends \
    wget \
 && wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/cuda-keyring_1.0-1_all.deb \
 && dpkg -i cuda-keyring_1.0-1_all.deb \
 && rm -f cuda-keyring_1.0-1_all.deb


RUN apt-get clean && \
    apt-get -y update && \
    apt-get install -y --no-install-recommends \
    nano curl git zip htop unzip tmux ca-certificates sudo bzip2 libx11-6 \
    build-essential vim gcc g++ make openssl ffmpeg libssl-dev libbz2-dev libboost-all-dev \
    libreadline-dev libsqlite3-dev python3-tk tk-dev python-tk libfreetype6-dev \
    libffi-dev libaio-dev openmpi-bin openmpi-doc libopenmpi-dev liblzma-dev libncurses-dev libsndfile1 \
    # add basic apt packages
    && apt-get clean \ 
    && rm -rf /var/lib/apt/lists/*


RUN apt update && apt install -y --no-install-recommends apt-transport-https gnupg && \
    curl -fsSL https://bazel.build/bazel-release.pub.gpg | gpg --dearmor >bazel-archive-keyring.gpg && \
    mv bazel-archive-keyring.gpg /usr/share/keyrings && \
    echo "deb [arch=amd64 signed-by=/usr/share/keyrings/bazel-archive-keyring.gpg] https://storage.googleapis.com/bazel-apt stable jdk1.8" > /etc/apt/sources.list.d/bazel.list && \
    apt update && apt install -y --no-install-recommends bazel && \
    apt install -y --no-install-recommends bazel-5.3.2 \
    && apt-get clean \ 
    && rm -rf /var/lib/apt/lists/*

RUN apt-get update & \
    python -m pip install --upgrade pip
RUN pip uninstall torch -y
RUN pip install --extra-index-url https://download.pytorch.org/whl/cu121 \
    torch==2.5.1+cu121 torchvision==0.20.1+cu121 torchaudio==2.5.1+cu121
RUN pip install colorlog==6.9.0 tqdm torchlibrosa==0.1.0 resampy==0.2.2
RUN pip install encodec torchopenl3==1.0.1 laion-clap==1.1.7
RUN pip install passt@git+https://github.com/hkchengrex/passt_hear21.git
RUN pip install mauve-text
RUN pip install numpy==1.25.0
RUN pip uninstall -y transformer-engine
RUN pip uninstall -y apex

# ENV http_proxy= \
#     https_proxy= \
#     HTTP_PROXY= \
#     HTTPS_PROXY=